# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class AutoSaveParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AutoSaveParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAutoSaveParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AutoSaveParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AutoSaveParameters
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # AutoSaveParameters
    def FolderPath(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AutoSaveParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    AutoSaveParametersStart(builder)

def AutoSaveParametersAddMode(builder: flatbuffers.Builder, mode: int):
    builder.PrependInt8Slot(0, mode, 0)

def AddMode(builder: flatbuffers.Builder, mode: int):
    AutoSaveParametersAddMode(builder, mode)

def AutoSaveParametersAddFolderPath(builder: flatbuffers.Builder, folderPath: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(folderPath), 0)

def AddFolderPath(builder: flatbuffers.Builder, folderPath: int):
    AutoSaveParametersAddFolderPath(builder, folderPath)

def AutoSaveParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AutoSaveParametersEnd(builder)
