from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.AutoSaveMode import AutoSaveMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class AutoSaveParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> AutoSaveParameters: ...
  @classmethod
  def GetRootAsAutoSaveParameters(cls, buf: bytes, offset: int) -> AutoSaveParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Mode(self) -> typing.Literal[AutoSaveMode.None_, AutoSaveMode.PerSweep, AutoSaveMode.PerCycle]: ...
  def FolderPath(self) -> str | None: ...
def AutoSaveParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def AutoSaveParametersAddMode(builder: flatbuffers.Builder, mode: typing.Literal[AutoSaveMode.None_, AutoSaveMode.PerSweep, AutoSaveMode.PerCycle]) -> None: ...
def AutoSaveParametersAddFolderPath(builder: flatbuffers.Builder, folderPath: uoffset) -> None: ...
def AutoSaveParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

