from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class DeviceKey(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> DeviceKey: ...
  @classmethod
  def GetRootAsDeviceKey(cls, buf: bytes, offset: int) -> DeviceKey: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ProductName(self) -> str | None: ...
  def SerialNumber(self) -> str | None: ...
def DeviceKeyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def DeviceKeyAddProductName(builder: flatbuffers.Builder, productName: uoffset) -> None: ...
def DeviceKeyAddSerialNumber(builder: flatbuffers.Builder, serialNumber: uoffset) -> None: ...
def DeviceKeyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

