# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class DeviceKey(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DeviceKey()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDeviceKey(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DeviceKey
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DeviceKey
    def ProductName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DeviceKey
    def SerialNumber(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DeviceKeyStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    DeviceKeyStart(builder)

def DeviceKeyAddProductName(builder: flatbuffers.Builder, productName: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(productName), 0)

def AddProductName(builder: flatbuffers.Builder, productName: int):
    DeviceKeyAddProductName(builder, productName)

def DeviceKeyAddSerialNumber(builder: flatbuffers.Builder, serialNumber: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(serialNumber), 0)

def AddSerialNumber(builder: flatbuffers.Builder, serialNumber: int):
    DeviceKeyAddSerialNumber(builder, serialNumber)

def DeviceKeyEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DeviceKeyEnd(builder)
