from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LMSLoggingParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LMSLoggingParameters: ...
  @classmethod
  def GetRootAsLMSLoggingParameters(cls, buf: bytes, offset: int) -> LMSLoggingParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def ChannelNumber(self) -> int: ...
  def Ranges(self, i: int) -> PowerRange | None: ...
  def RangesLength(self) -> int: ...
  def RangesIsNone(self) -> bool: ...
def LMSLoggingParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LMSLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def LMSLoggingParametersAddChannelNumber(builder: flatbuffers.Builder, channelNumber: int) -> None: ...
def LMSLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: uoffset) -> None: ...
def LMSLoggingParametersStartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def LMSLoggingParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

