# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class LMSModuleParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LMSModuleParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLMSModuleParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LMSModuleParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LMSModuleParameters
    def ModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LMSModuleParameters
    def AutoRangeMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LMSModuleParameters
    def TriggerInput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # LMSModuleParameters
    def TriggerInputRearm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # LMSModuleParameters
    def TriggerOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def LMSModuleParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    LMSModuleParametersStart(builder)

def LMSModuleParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    builder.PrependInt32Slot(0, moduleNumber, 0)

def AddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    LMSModuleParametersAddModuleNumber(builder, moduleNumber)

def LMSModuleParametersAddAutoRangeMode(builder: flatbuffers.Builder, autoRangeMode: bool):
    builder.PrependBoolSlot(1, autoRangeMode, 0)

def AddAutoRangeMode(builder: flatbuffers.Builder, autoRangeMode: bool):
    LMSModuleParametersAddAutoRangeMode(builder, autoRangeMode)

def LMSModuleParametersAddTriggerInput(builder: flatbuffers.Builder, triggerInput: int):
    builder.PrependInt8Slot(2, triggerInput, 0)

def AddTriggerInput(builder: flatbuffers.Builder, triggerInput: int):
    LMSModuleParametersAddTriggerInput(builder, triggerInput)

def LMSModuleParametersAddTriggerInputRearm(builder: flatbuffers.Builder, triggerInputRearm: bool):
    builder.PrependBoolSlot(3, triggerInputRearm, 0)

def AddTriggerInputRearm(builder: flatbuffers.Builder, triggerInputRearm: bool):
    LMSModuleParametersAddTriggerInputRearm(builder, triggerInputRearm)

def LMSModuleParametersAddTriggerOutput(builder: flatbuffers.Builder, triggerOutput: int):
    builder.PrependInt8Slot(4, triggerOutput, 0)

def AddTriggerOutput(builder: flatbuffers.Builder, triggerOutput: int):
    LMSModuleParametersAddTriggerOutput(builder, triggerOutput)

def LMSModuleParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return LMSModuleParametersEnd(builder)
