from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.LMSModuleParameters import LMSModuleParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LMSModuleParametersEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LMSModuleParametersEntry: ...
  @classmethod
  def GetRootAsLMSModuleParametersEntry(cls, buf: bytes, offset: int) -> LMSModuleParametersEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> int: ...
  def Value(self) -> LMSModuleParameters | None: ...
def LMSModuleParametersEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LMSModuleParametersEntryAddKey(builder: flatbuffers.Builder, key: int) -> None: ...
def LMSModuleParametersEntryAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def LMSModuleParametersEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

