from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.ThirdParty.Native.Agilent.LMS.Enums.TriggerInputResponse import TriggerInputResponse
from Santec.Instruments.ThirdParty.Native.Agilent.LMS.Enums.TriggerOutputResponse import TriggerOutputResponse

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LMSModuleParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LMSModuleParameters: ...
  @classmethod
  def GetRootAsLMSModuleParameters(cls, buf: bytes, offset: int) -> LMSModuleParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def AutoRangeMode(self) -> bool: ...
  def TriggerInput(self) -> typing.Literal[TriggerInputResponse.Ignore, TriggerInputResponse.SMEasure, TriggerInputResponse.CMEasure, TriggerInputResponse.NextStep, TriggerInputResponse.SWStart]: ...
  def TriggerInputRearm(self) -> bool: ...
  def TriggerOutput(self) -> typing.Literal[TriggerOutputResponse.Disable, TriggerOutputResponse.AVGover, TriggerOutputResponse.Measure, TriggerOutputResponse.Modulation, TriggerOutputResponse.STFinished, TriggerOutputResponse.SWFinished, TriggerOutputResponse.SWStarted]: ...
def LMSModuleParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LMSModuleParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def LMSModuleParametersAddAutoRangeMode(builder: flatbuffers.Builder, autoRangeMode: bool) -> None: ...
def LMSModuleParametersAddTriggerInput(builder: flatbuffers.Builder, triggerInput: typing.Literal[TriggerInputResponse.Ignore, TriggerInputResponse.SMEasure, TriggerInputResponse.CMEasure, TriggerInputResponse.NextStep, TriggerInputResponse.SWStart]) -> None: ...
def LMSModuleParametersAddTriggerInputRearm(builder: flatbuffers.Builder, triggerInputRearm: bool) -> None: ...
def LMSModuleParametersAddTriggerOutput(builder: flatbuffers.Builder, triggerOutput: typing.Literal[TriggerOutputResponse.Disable, TriggerOutputResponse.AVGover, TriggerOutputResponse.Measure, TriggerOutputResponse.Modulation, TriggerOutputResponse.STFinished, TriggerOutputResponse.SWFinished, TriggerOutputResponse.SWStarted]) -> None: ...
def LMSModuleParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

