# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.LMSLoggingParameters import LMSLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.LMSModuleParameters import LMSModuleParameters
from typing import Optional
np = import_numpy()

class LMSParametersEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LMSParametersEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLMSParametersEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LMSParametersEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LMSParametersEntry
    def Module(self) -> Optional[LMSModuleParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = LMSModuleParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LMSParametersEntry
    def Logging(self) -> Optional[LMSLoggingParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = LMSLoggingParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LMSParametersEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    LMSParametersEntryStart(builder)

def LMSParametersEntryAddModule(builder: flatbuffers.Builder, module: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(module), 0)

def AddModule(builder: flatbuffers.Builder, module: int):
    LMSParametersEntryAddModule(builder, module)

def LMSParametersEntryAddLogging(builder: flatbuffers.Builder, logging: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(logging), 0)

def AddLogging(builder: flatbuffers.Builder, logging: int):
    LMSParametersEntryAddLogging(builder, logging)

def LMSParametersEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return LMSParametersEntryEnd(builder)
