from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.LMSLoggingParameters import LMSLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.LMSModuleParameters import LMSModuleParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class LMSParametersEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> LMSParametersEntry: ...
  @classmethod
  def GetRootAsLMSParametersEntry(cls, buf: bytes, offset: int) -> LMSParametersEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Module(self) -> LMSModuleParameters | None: ...
  def Logging(self) -> LMSLoggingParameters | None: ...
def LMSParametersEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def LMSParametersEntryAddModule(builder: flatbuffers.Builder, module: uoffset) -> None: ...
def LMSParametersEntryAddLogging(builder: flatbuffers.Builder, logging: uoffset) -> None: ...
def LMSParametersEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

