from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.DeviceKey import DeviceKey
from Santec.STSProcess.Process.Native.Parameters.MPMLoggingParameters import MPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.MPMParameters import MPMParameters
from Santec.STSProcess.Process.Native.Parameters.SPUParameters import SPUParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MPMGroup(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MPMGroup: ...
  @classmethod
  def GetRootAsMPMGroup(cls, buf: bytes, offset: int) -> MPMGroup: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MpmKey(self) -> DeviceKey | None: ...
  def MpmParameters(self) -> MPMParameters | None: ...
  def MpmLoggingParameters(self, i: int) -> MPMLoggingParameters | None: ...
  def MpmLoggingParametersLength(self) -> int: ...
  def MpmLoggingParametersIsNone(self) -> bool: ...
  def SpuKey(self) -> DeviceKey | None: ...
  def SpuParameters(self) -> SPUParameters | None: ...
def MPMGroupStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MPMGroupAddMpmKey(builder: flatbuffers.Builder, mpmKey: uoffset) -> None: ...
def MPMGroupAddMpmParameters(builder: flatbuffers.Builder, mpmParameters: uoffset) -> None: ...
def MPMGroupAddMpmLoggingParameters(builder: flatbuffers.Builder, mpmLoggingParameters: uoffset) -> None: ...
def MPMGroupStartMpmLoggingParametersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMpmLoggingParametersVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MPMGroupAddSpuKey(builder: flatbuffers.Builder, spuKey: uoffset) -> None: ...
def MPMGroupAddSpuParameters(builder: flatbuffers.Builder, spuParameters: uoffset) -> None: ...
def MPMGroupEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

