# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.DeviceKey import DeviceKey
from Santec.STSProcess.Process.Native.Parameters.MPMLoggingParameters import MPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.MPMParameters import MPMParameters
from Santec.STSProcess.Process.Native.Parameters.SPUParameters import SPUParameters
from typing import Optional
np = import_numpy()

class MPMGroup(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MPMGroup()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMPMGroup(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MPMGroup
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MPMGroup
    def MpmKey(self) -> Optional[DeviceKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DeviceKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMGroup
    def MpmParameters(self) -> Optional[MPMParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MPMParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMGroup
    def MpmLoggingParameters(self, j: int) -> Optional[MPMLoggingParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = MPMLoggingParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMGroup
    def MpmLoggingParametersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MPMGroup
    def MpmLoggingParametersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MPMGroup
    def SpuKey(self) -> Optional[DeviceKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DeviceKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMGroup
    def SpuParameters(self) -> Optional[SPUParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SPUParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MPMGroupStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    MPMGroupStart(builder)

def MPMGroupAddMpmKey(builder: flatbuffers.Builder, mpmKey: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mpmKey), 0)

def AddMpmKey(builder: flatbuffers.Builder, mpmKey: int):
    MPMGroupAddMpmKey(builder, mpmKey)

def MPMGroupAddMpmParameters(builder: flatbuffers.Builder, mpmParameters: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mpmParameters), 0)

def AddMpmParameters(builder: flatbuffers.Builder, mpmParameters: int):
    MPMGroupAddMpmParameters(builder, mpmParameters)

def MPMGroupAddMpmLoggingParameters(builder: flatbuffers.Builder, mpmLoggingParameters: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(mpmLoggingParameters), 0)

def AddMpmLoggingParameters(builder: flatbuffers.Builder, mpmLoggingParameters: int):
    MPMGroupAddMpmLoggingParameters(builder, mpmLoggingParameters)

def MPMGroupStartMpmLoggingParametersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartMpmLoggingParametersVector(builder, numElems: int) -> int:
    return MPMGroupStartMpmLoggingParametersVector(builder, numElems)

def MPMGroupAddSpuKey(builder: flatbuffers.Builder, spuKey: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(spuKey), 0)

def AddSpuKey(builder: flatbuffers.Builder, spuKey: int):
    MPMGroupAddSpuKey(builder, spuKey)

def MPMGroupAddSpuParameters(builder: flatbuffers.Builder, spuParameters: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(spuParameters), 0)

def AddSpuParameters(builder: flatbuffers.Builder, spuParameters: int):
    MPMGroupAddSpuParameters(builder, spuParameters)

def MPMGroupEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MPMGroupEnd(builder)
