# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange
from typing import Optional
np = import_numpy()

class MPMLoggingParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MPMLoggingParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMPMLoggingParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MPMLoggingParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MPMLoggingParameters
    def ModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MPMLoggingParameters
    def ChannelNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MPMLoggingParameters
    def Ranges(self, j: int) -> Optional[PowerRange]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PowerRange()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMLoggingParameters
    def RangesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MPMLoggingParameters
    def RangesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # MPMLoggingParameters
    def MeasurementMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MPMLoggingParameters
    def MonitorMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def MPMLoggingParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    MPMLoggingParametersStart(builder)

def MPMLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    builder.PrependInt32Slot(0, moduleNumber, 0)

def AddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    MPMLoggingParametersAddModuleNumber(builder, moduleNumber)

def MPMLoggingParametersAddChannelNumber(builder: flatbuffers.Builder, channelNumber: int):
    builder.PrependInt32Slot(1, channelNumber, 0)

def AddChannelNumber(builder: flatbuffers.Builder, channelNumber: int):
    MPMLoggingParametersAddChannelNumber(builder, channelNumber)

def MPMLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ranges), 0)

def AddRanges(builder: flatbuffers.Builder, ranges: int):
    MPMLoggingParametersAddRanges(builder, ranges)

def MPMLoggingParametersStartRangesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRangesVector(builder, numElems: int) -> int:
    return MPMLoggingParametersStartRangesVector(builder, numElems)

def MPMLoggingParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    builder.PrependInt8Slot(3, measurementMode, 0)

def AddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    MPMLoggingParametersAddMeasurementMode(builder, measurementMode)

def MPMLoggingParametersAddMonitorMode(builder: flatbuffers.Builder, monitorMode: int):
    builder.PrependInt8Slot(4, monitorMode, 0)

def AddMonitorMode(builder: flatbuffers.Builder, monitorMode: int):
    MPMLoggingParametersAddMonitorMode(builder, monitorMode)

def MPMLoggingParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MPMLoggingParametersEnd(builder)
