from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.MeasurementMode import MeasurementMode
from Santec.STSProcess.Process.Native.Common.PowerMonitorMode import PowerMonitorMode
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MPMLoggingParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MPMLoggingParameters: ...
  @classmethod
  def GetRootAsMPMLoggingParameters(cls, buf: bytes, offset: int) -> MPMLoggingParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def ChannelNumber(self) -> int: ...
  def Ranges(self, i: int) -> PowerRange | None: ...
  def RangesLength(self) -> int: ...
  def RangesIsNone(self) -> bool: ...
  def MeasurementMode(self) -> typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]: ...
  def MonitorMode(self) -> typing.Literal[PowerMonitorMode.Unknown, PowerMonitorMode.TSLMonitor, PowerMonitorMode.MPMChannel, PowerMonitorMode.SPUMonitor]: ...
def MPMLoggingParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MPMLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def MPMLoggingParametersAddChannelNumber(builder: flatbuffers.Builder, channelNumber: int) -> None: ...
def MPMLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: uoffset) -> None: ...
def MPMLoggingParametersStartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def MPMLoggingParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]) -> None: ...
def MPMLoggingParametersAddMonitorMode(builder: flatbuffers.Builder, monitorMode: typing.Literal[PowerMonitorMode.Unknown, PowerMonitorMode.TSLMonitor, PowerMonitorMode.MPMChannel, PowerMonitorMode.SPUMonitor]) -> None: ...
def MPMLoggingParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

