# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MPMParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MPMParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMPMParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MPMParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MPMParameters
    def MeasurementMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MPMParameters
    def HighSpecMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MPMParameters
    def PowerMonitorModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MPMParameters
    def PowerMonitorChannelNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MPMParameters
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MPMParameters
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MPMParameters
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MPMParameters
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MPMParameters
    def ReturnLossMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MPMParameters
    def ReturnLossModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MPMParameters
    def ReturnLossChannelNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MPMParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(11)

def Start(builder: flatbuffers.Builder):
    MPMParametersStart(builder)

def MPMParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    builder.PrependInt8Slot(0, measurementMode, 0)

def AddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    MPMParametersAddMeasurementMode(builder, measurementMode)

def MPMParametersAddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool):
    builder.PrependBoolSlot(1, highSpecMode, 0)

def AddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool):
    MPMParametersAddHighSpecMode(builder, highSpecMode)

def MPMParametersAddPowerMonitorModuleNumber(builder: flatbuffers.Builder, powerMonitorModuleNumber: int):
    builder.PrependInt32Slot(2, powerMonitorModuleNumber, 0)

def AddPowerMonitorModuleNumber(builder: flatbuffers.Builder, powerMonitorModuleNumber: int):
    MPMParametersAddPowerMonitorModuleNumber(builder, powerMonitorModuleNumber)

def MPMParametersAddPowerMonitorChannelNumber(builder: flatbuffers.Builder, powerMonitorChannelNumber: int):
    builder.PrependInt32Slot(3, powerMonitorChannelNumber, 0)

def AddPowerMonitorChannelNumber(builder: flatbuffers.Builder, powerMonitorChannelNumber: int):
    MPMParametersAddPowerMonitorChannelNumber(builder, powerMonitorChannelNumber)

def MPMParametersAddStart(builder: flatbuffers.Builder, start: float):
    builder.PrependFloat64Slot(4, start, 0.0)

def AddStart(builder: flatbuffers.Builder, start: float):
    MPMParametersAddStart(builder, start)

def MPMParametersAddStop(builder: flatbuffers.Builder, stop: float):
    builder.PrependFloat64Slot(5, stop, 0.0)

def AddStop(builder: flatbuffers.Builder, stop: float):
    MPMParametersAddStop(builder, stop)

def MPMParametersAddStep(builder: flatbuffers.Builder, step: float):
    builder.PrependFloat64Slot(6, step, 0.0)

def AddStep(builder: flatbuffers.Builder, step: float):
    MPMParametersAddStep(builder, step)

def MPMParametersAddSpeed(builder: flatbuffers.Builder, speed: float):
    builder.PrependFloat64Slot(7, speed, 0.0)

def AddSpeed(builder: flatbuffers.Builder, speed: float):
    MPMParametersAddSpeed(builder, speed)

def MPMParametersAddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool):
    builder.PrependBoolSlot(8, returnLossMode, 0)

def AddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool):
    MPMParametersAddReturnLossMode(builder, returnLossMode)

def MPMParametersAddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int):
    builder.PrependInt32Slot(9, returnLossModuleNumber, 0)

def AddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int):
    MPMParametersAddReturnLossModuleNumber(builder, returnLossModuleNumber)

def MPMParametersAddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int):
    builder.PrependInt32Slot(10, returnLossChannelNumber, 0)

def AddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int):
    MPMParametersAddReturnLossChannelNumber(builder, returnLossChannelNumber)

def MPMParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MPMParametersEnd(builder)
