# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.MPMLoggingParameters import MPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.MPMParameters import MPMParameters
from typing import Optional
np = import_numpy()

class MPMParametersEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MPMParametersEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMPMParametersEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MPMParametersEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MPMParametersEntry
    def Module(self) -> Optional[MPMParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MPMParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MPMParametersEntry
    def Logging(self) -> Optional[MPMLoggingParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MPMLoggingParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MPMParametersEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    MPMParametersEntryStart(builder)

def MPMParametersEntryAddModule(builder: flatbuffers.Builder, module: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(module), 0)

def AddModule(builder: flatbuffers.Builder, module: int):
    MPMParametersEntryAddModule(builder, module)

def MPMParametersEntryAddLogging(builder: flatbuffers.Builder, logging: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(logging), 0)

def AddLogging(builder: flatbuffers.Builder, logging: int):
    MPMParametersEntryAddLogging(builder, logging)

def MPMParametersEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MPMParametersEntryEnd(builder)
