from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.MPM.MeasurementMode import MeasurementMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MPMParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MPMParameters: ...
  @classmethod
  def GetRootAsMPMParameters(cls, buf: bytes, offset: int) -> MPMParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MeasurementMode(self) -> typing.Literal[MeasurementMode.ManualRangeConstant, MeasurementMode.ManualRangeSweep, MeasurementMode.AutoRangeConstant, MeasurementMode.AutoRangeSweep, MeasurementMode.FreeRun]: ...
  def HighSpecMode(self) -> bool: ...
  def PowerMonitorModuleNumber(self) -> int: ...
  def PowerMonitorChannelNumber(self) -> int: ...
  def Start(self) -> float: ...
  def Stop(self) -> float: ...
  def Step(self) -> float: ...
  def Speed(self) -> float: ...
  def ReturnLossMode(self) -> bool: ...
  def ReturnLossModuleNumber(self) -> int: ...
  def ReturnLossChannelNumber(self) -> int: ...
def MPMParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MPMParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: typing.Literal[MeasurementMode.ManualRangeConstant, MeasurementMode.ManualRangeSweep, MeasurementMode.AutoRangeConstant, MeasurementMode.AutoRangeSweep, MeasurementMode.FreeRun]) -> None: ...
def MPMParametersAddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool) -> None: ...
def MPMParametersAddPowerMonitorModuleNumber(builder: flatbuffers.Builder, powerMonitorModuleNumber: int) -> None: ...
def MPMParametersAddPowerMonitorChannelNumber(builder: flatbuffers.Builder, powerMonitorChannelNumber: int) -> None: ...
def MPMParametersAddStart(builder: flatbuffers.Builder, start: float) -> None: ...
def MPMParametersAddStop(builder: flatbuffers.Builder, stop: float) -> None: ...
def MPMParametersAddStep(builder: flatbuffers.Builder, step: float) -> None: ...
def MPMParametersAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def MPMParametersAddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool) -> None: ...
def MPMParametersAddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int) -> None: ...
def MPMParametersAddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int) -> None: ...
def MPMParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

