from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.MPMLoggingParameters import MPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.MPMParameters import MPMParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MPMParametersEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MPMParametersEntry: ...
  @classmethod
  def GetRootAsMPMParametersEntry(cls, buf: bytes, offset: int) -> MPMParametersEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Module(self) -> MPMParameters | None: ...
  def Logging(self) -> MPMLoggingParameters | None: ...
def MPMParametersEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MPMParametersEntryAddModule(builder: flatbuffers.Builder, module: uoffset) -> None: ...
def MPMParametersEntryAddLogging(builder: flatbuffers.Builder, logging: uoffset) -> None: ...
def MPMParametersEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

