from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OPMLoggingParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OPMLoggingParameters: ...
  @classmethod
  def GetRootAsOPMLoggingParameters(cls, buf: bytes, offset: int) -> OPMLoggingParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def Ranges(self, i: int) -> PowerRange | None: ...
  def RangesLength(self) -> int: ...
  def RangesIsNone(self) -> bool: ...
def OPMLoggingParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OPMLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def OPMLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: uoffset) -> None: ...
def OPMLoggingParametersStartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def OPMLoggingParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

