# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange
from typing import Optional
np = import_numpy()

class OPMLoggingParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OPMLoggingParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOPMLoggingParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OPMLoggingParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OPMLoggingParameters
    def ModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OPMLoggingParameters
    def Ranges(self, j: int) -> Optional[PowerRange]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PowerRange()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OPMLoggingParameters
    def RangesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OPMLoggingParameters
    def RangesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def OPMLoggingParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    OPMLoggingParametersStart(builder)

def OPMLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    builder.PrependInt32Slot(0, moduleNumber, 0)

def AddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    OPMLoggingParametersAddModuleNumber(builder, moduleNumber)

def OPMLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ranges), 0)

def AddRanges(builder: flatbuffers.Builder, ranges: int):
    OPMLoggingParametersAddRanges(builder, ranges)

def OPMLoggingParametersStartRangesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRangesVector(builder, numElems: int) -> int:
    return OPMLoggingParametersStartRangesVector(builder, numElems)

def OPMLoggingParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OPMLoggingParametersEnd(builder)
