# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.OPMModuleParameters import OPMModuleParameters
from typing import Optional
np = import_numpy()

class OPMModuleParametersEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OPMModuleParametersEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOPMModuleParametersEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OPMModuleParametersEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OPMModuleParametersEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OPMModuleParametersEntry
    def Value(self) -> Optional[OPMModuleParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = OPMModuleParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OPMModuleParametersEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    OPMModuleParametersEntryStart(builder)

def OPMModuleParametersEntryAddKey(builder: flatbuffers.Builder, key: int):
    builder.PrependInt32Slot(0, key, 0)

def AddKey(builder: flatbuffers.Builder, key: int):
    OPMModuleParametersEntryAddKey(builder, key)

def OPMModuleParametersEntryAddValue(builder: flatbuffers.Builder, value: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder: flatbuffers.Builder, value: int):
    OPMModuleParametersEntryAddValue(builder, value)

def OPMModuleParametersEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OPMModuleParametersEntryEnd(builder)
