from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.OPM.TriggerEdge import TriggerEdge
from Santec.Instruments.Native.Enums.OPM.TriggerMode import TriggerMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OPMModuleParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OPMModuleParameters: ...
  @classmethod
  def GetRootAsOPMModuleParameters(cls, buf: bytes, offset: int) -> OPMModuleParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def TriggerMode(self) -> typing.Literal[TriggerMode.Ignore, TriggerMode.SME, TriggerMode.FreeRun]: ...
  def TriggerEdge(self) -> typing.Literal[TriggerEdge.Rising, TriggerEdge.Falling]: ...
def OPMModuleParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OPMModuleParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def OPMModuleParametersAddTriggerMode(builder: flatbuffers.Builder, triggerMode: typing.Literal[TriggerMode.Ignore, TriggerMode.SME, TriggerMode.FreeRun]) -> None: ...
def OPMModuleParametersAddTriggerEdge(builder: flatbuffers.Builder, triggerEdge: typing.Literal[TriggerEdge.Rising, TriggerEdge.Falling]) -> None: ...
def OPMModuleParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

