from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.OPMModuleParameters import OPMModuleParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OPMModuleParametersEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OPMModuleParametersEntry: ...
  @classmethod
  def GetRootAsOPMModuleParametersEntry(cls, buf: bytes, offset: int) -> OPMModuleParametersEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> int: ...
  def Value(self) -> OPMModuleParameters | None: ...
def OPMModuleParametersEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OPMModuleParametersEntryAddKey(builder: flatbuffers.Builder, key: int) -> None: ...
def OPMModuleParametersEntryAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def OPMModuleParametersEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

