# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class OPMModuleParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OPMModuleParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOPMModuleParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OPMModuleParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OPMModuleParameters
    def ModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # OPMModuleParameters
    def TriggerMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # OPMModuleParameters
    def TriggerEdge(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def OPMModuleParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    OPMModuleParametersStart(builder)

def OPMModuleParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    builder.PrependInt32Slot(0, moduleNumber, 0)

def AddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    OPMModuleParametersAddModuleNumber(builder, moduleNumber)

def OPMModuleParametersAddTriggerMode(builder: flatbuffers.Builder, triggerMode: int):
    builder.PrependInt8Slot(1, triggerMode, 0)

def AddTriggerMode(builder: flatbuffers.Builder, triggerMode: int):
    OPMModuleParametersAddTriggerMode(builder, triggerMode)

def OPMModuleParametersAddTriggerEdge(builder: flatbuffers.Builder, triggerEdge: int):
    builder.PrependInt8Slot(2, triggerEdge, 0)

def AddTriggerEdge(builder: flatbuffers.Builder, triggerEdge: int):
    OPMModuleParametersAddTriggerEdge(builder, triggerEdge)

def OPMModuleParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OPMModuleParametersEnd(builder)
