# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.OPMLoggingParameters import OPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.OPMModuleParameters import OPMModuleParameters
from typing import Optional
np = import_numpy()

class OPMParametersEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OPMParametersEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOPMParametersEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OPMParametersEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OPMParametersEntry
    def Module(self) -> Optional[OPMModuleParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = OPMModuleParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OPMParametersEntry
    def Logging(self) -> Optional[OPMLoggingParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = OPMLoggingParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OPMParametersEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    OPMParametersEntryStart(builder)

def OPMParametersEntryAddModule(builder: flatbuffers.Builder, module: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(module), 0)

def AddModule(builder: flatbuffers.Builder, module: int):
    OPMParametersEntryAddModule(builder, module)

def OPMParametersEntryAddLogging(builder: flatbuffers.Builder, logging: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(logging), 0)

def AddLogging(builder: flatbuffers.Builder, logging: int):
    OPMParametersEntryAddLogging(builder, logging)

def OPMParametersEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OPMParametersEntryEnd(builder)
