from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.OPMLoggingParameters import OPMLoggingParameters
from Santec.STSProcess.Process.Native.Parameters.OPMModuleParameters import OPMModuleParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OPMParametersEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OPMParametersEntry: ...
  @classmethod
  def GetRootAsOPMParametersEntry(cls, buf: bytes, offset: int) -> OPMParametersEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Module(self) -> OPMModuleParameters | None: ...
  def Logging(self) -> OPMLoggingParameters | None: ...
def OPMParametersEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OPMParametersEntryAddModule(builder: flatbuffers.Builder, module: uoffset) -> None: ...
def OPMParametersEntryAddLogging(builder: flatbuffers.Builder, logging: uoffset) -> None: ...
def OPMParametersEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

