# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.DeviceKey import DeviceKey
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

class OSXOutputPortParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OSXOutputPortParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOSXOutputPortParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OSXOutputPortParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OSXOutputPortParameters
    def PowerMeterKey(self) -> Optional[DeviceKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DeviceKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OSXOutputPortParameters
    def OutputPort(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # OSXOutputPortParameters
    def PowerMeterParametersType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # OSXOutputPortParameters
    def PowerMeterParameters(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def OSXOutputPortParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    OSXOutputPortParametersStart(builder)

def OSXOutputPortParametersAddPowerMeterKey(builder: flatbuffers.Builder, powerMeterKey: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(powerMeterKey), 0)

def AddPowerMeterKey(builder: flatbuffers.Builder, powerMeterKey: int):
    OSXOutputPortParametersAddPowerMeterKey(builder, powerMeterKey)

def OSXOutputPortParametersAddOutputPort(builder: flatbuffers.Builder, outputPort: int):
    builder.PrependUint16Slot(1, outputPort, 0)

def AddOutputPort(builder: flatbuffers.Builder, outputPort: int):
    OSXOutputPortParametersAddOutputPort(builder, outputPort)

def OSXOutputPortParametersAddPowerMeterParametersType(builder: flatbuffers.Builder, powerMeterParametersType: int):
    builder.PrependUint8Slot(2, powerMeterParametersType, 0)

def AddPowerMeterParametersType(builder: flatbuffers.Builder, powerMeterParametersType: int):
    OSXOutputPortParametersAddPowerMeterParametersType(builder, powerMeterParametersType)

def OSXOutputPortParametersAddPowerMeterParameters(builder: flatbuffers.Builder, powerMeterParameters: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(powerMeterParameters), 0)

def AddPowerMeterParameters(builder: flatbuffers.Builder, powerMeterParameters: int):
    OSXOutputPortParametersAddPowerMeterParameters(builder, powerMeterParameters)

def OSXOutputPortParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OSXOutputPortParametersEnd(builder)
