from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.DeviceKey import DeviceKey
from Santec.STSProcess.Process.Native.Parameters.PowerMeterParameters import PowerMeterParameters
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OSXOutputPortParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OSXOutputPortParameters: ...
  @classmethod
  def GetRootAsOSXOutputPortParameters(cls, buf: bytes, offset: int) -> OSXOutputPortParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PowerMeterKey(self) -> DeviceKey | None: ...
  def OutputPort(self) -> int: ...
  def PowerMeterParametersType(self) -> typing.Literal[PowerMeterParameters.NONE, PowerMeterParameters.MPM, PowerMeterParameters.OPM]: ...
  def PowerMeterParameters(self) -> table.Table | None: ...
def OSXOutputPortParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OSXOutputPortParametersAddPowerMeterKey(builder: flatbuffers.Builder, powerMeterKey: uoffset) -> None: ...
def OSXOutputPortParametersAddOutputPort(builder: flatbuffers.Builder, outputPort: int) -> None: ...
def OSXOutputPortParametersAddPowerMeterParametersType(builder: flatbuffers.Builder, powerMeterParametersType: typing.Literal[PowerMeterParameters.NONE, PowerMeterParameters.MPM, PowerMeterParameters.OPM]) -> None: ...
def OSXOutputPortParametersAddPowerMeterParameters(builder: flatbuffers.Builder, powerMeterParameters: uoffset) -> None: ...
def OSXOutputPortParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

