# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.OSXOutputPortParameters import OSXOutputPortParameters
from typing import Optional
np = import_numpy()

class OSXParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OSXParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOSXParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OSXParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OSXParameters
    def Common(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # OSXParameters
    def OutputPorts(self, j: int) -> Optional[OSXOutputPortParameters]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = OSXOutputPortParameters()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OSXParameters
    def OutputPortsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OSXParameters
    def OutputPortsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def OSXParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    OSXParametersStart(builder)

def OSXParametersAddCommon(builder: flatbuffers.Builder, common: int):
    builder.PrependUint16Slot(0, common, 0)

def AddCommon(builder: flatbuffers.Builder, common: int):
    OSXParametersAddCommon(builder, common)

def OSXParametersAddOutputPorts(builder: flatbuffers.Builder, outputPorts: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outputPorts), 0)

def AddOutputPorts(builder: flatbuffers.Builder, outputPorts: int):
    OSXParametersAddOutputPorts(builder, outputPorts)

def OSXParametersStartOutputPortsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOutputPortsVector(builder, numElems: int) -> int:
    return OSXParametersStartOutputPortsVector(builder, numElems)

def OSXParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return OSXParametersEnd(builder)
