from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Parameters.OSXOutputPortParameters import OSXOutputPortParameters

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class OSXParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> OSXParameters: ...
  @classmethod
  def GetRootAsOSXParameters(cls, buf: bytes, offset: int) -> OSXParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Common(self) -> int: ...
  def OutputPorts(self, i: int) -> OSXOutputPortParameters | None: ...
  def OutputPortsLength(self) -> int: ...
  def OutputPortsIsNone(self) -> bool: ...
def OSXParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def OSXParametersAddCommon(builder: flatbuffers.Builder, common: int) -> None: ...
def OSXParametersAddOutputPorts(builder: flatbuffers.Builder, outputPorts: uoffset) -> None: ...
def OSXParametersStartOutputPortsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartOutputPortsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def OSXParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

