from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PCUParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PCUParameters: ...
  @classmethod
  def GetRootAsPCUParameters(cls, buf: bytes, offset: int) -> PCUParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Use2sop(self) -> bool: ...
  def Use6sop(self) -> bool: ...
def PCUParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PCUParametersAddUse2sop(builder: flatbuffers.Builder, use2sop: bool) -> None: ...
def PCUParametersAddUse6sop(builder: flatbuffers.Builder, use6sop: bool) -> None: ...
def PCUParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

