# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PCUParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PCUParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPCUParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PCUParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PCUParameters
    def Use2sop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PCUParameters
    def Use6sop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PCUParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    PCUParametersStart(builder)

def PCUParametersAddUse2sop(builder: flatbuffers.Builder, use2sop: bool):
    builder.PrependBoolSlot(0, use2sop, 0)

def AddUse2sop(builder: flatbuffers.Builder, use2sop: bool):
    PCUParametersAddUse2sop(builder, use2sop)

def PCUParametersAddUse6sop(builder: flatbuffers.Builder, use6sop: bool):
    builder.PrependBoolSlot(1, use6sop, 0)

def AddUse6sop(builder: flatbuffers.Builder, use6sop: bool):
    PCUParametersAddUse6sop(builder, use6sop)

def PCUParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PCUParametersEnd(builder)
