# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class PowerRange(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PowerRange()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPowerRange(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PowerRange
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PowerRange
    def MaxPower(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # PowerRange
    def MinPower(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # PowerRange
    def RangeNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def PowerRangeStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    PowerRangeStart(builder)

def PowerRangeAddMaxPower(builder: flatbuffers.Builder, maxPower: int):
    builder.PrependInt16Slot(0, maxPower, 0)

def AddMaxPower(builder: flatbuffers.Builder, maxPower: int):
    PowerRangeAddMaxPower(builder, maxPower)

def PowerRangeAddMinPower(builder: flatbuffers.Builder, minPower: int):
    builder.PrependInt16Slot(1, minPower, 0)

def AddMinPower(builder: flatbuffers.Builder, minPower: int):
    PowerRangeAddMinPower(builder, minPower)

def PowerRangeAddRangeNumber(builder: flatbuffers.Builder, rangeNumber: int):
    builder.PrependUint8Slot(2, rangeNumber, 0)

def AddRangeNumber(builder: flatbuffers.Builder, rangeNumber: int):
    PowerRangeAddRangeNumber(builder, rangeNumber)

def PowerRangeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PowerRangeEnd(builder)
