from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PowerRange(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> PowerRange: ...
  @classmethod
  def GetRootAsPowerRange(cls, buf: bytes, offset: int) -> PowerRange: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MaxPower(self) -> int: ...
  def MinPower(self) -> int: ...
  def RangeNumber(self) -> int: ...
def PowerRangeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PowerRangeAddMaxPower(builder: flatbuffers.Builder, maxPower: int) -> None: ...
def PowerRangeAddMinPower(builder: flatbuffers.Builder, minPower: int) -> None: ...
def PowerRangeAddRangeNumber(builder: flatbuffers.Builder, rangeNumber: int) -> None: ...
def PowerRangeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

