# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class SPUParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SPUParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSPUParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SPUParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SPUParameters
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SPUParameters
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SPUParameters
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SPUParameters
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SPUParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    SPUParametersStart(builder)

def SPUParametersAddStart(builder: flatbuffers.Builder, start: float):
    builder.PrependFloat64Slot(0, start, 0.0)

def AddStart(builder: flatbuffers.Builder, start: float):
    SPUParametersAddStart(builder, start)

def SPUParametersAddStop(builder: flatbuffers.Builder, stop: float):
    builder.PrependFloat64Slot(1, stop, 0.0)

def AddStop(builder: flatbuffers.Builder, stop: float):
    SPUParametersAddStop(builder, stop)

def SPUParametersAddStep(builder: flatbuffers.Builder, step: float):
    builder.PrependFloat64Slot(2, step, 0.0)

def AddStep(builder: flatbuffers.Builder, step: float):
    SPUParametersAddStep(builder, step)

def SPUParametersAddSpeed(builder: flatbuffers.Builder, speed: float):
    builder.PrependFloat64Slot(3, speed, 0.0)

def AddSpeed(builder: flatbuffers.Builder, speed: float):
    SPUParametersAddSpeed(builder, speed)

def SPUParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SPUParametersEnd(builder)
