from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class SPUParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> SPUParameters: ...
  @classmethod
  def GetRootAsSPUParameters(cls, buf: bytes, offset: int) -> SPUParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Start(self) -> float: ...
  def Stop(self) -> float: ...
  def Step(self) -> float: ...
  def Speed(self) -> float: ...
def SPUParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def SPUParametersAddStart(builder: flatbuffers.Builder, start: float) -> None: ...
def SPUParametersAddStop(builder: flatbuffers.Builder, stop: float) -> None: ...
def SPUParametersAddStep(builder: flatbuffers.Builder, step: float) -> None: ...
def SPUParametersAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def SPUParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

