from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.MeasurementMode import MeasurementMode
from Santec.STSProcess.Process.Native.Common.PowerMonitorMode import PowerMonitorMode
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class STPLoggingParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> STPLoggingParameters: ...
  @classmethod
  def GetRootAsSTPLoggingParameters(cls, buf: bytes, offset: int) -> STPLoggingParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ModuleNumber(self) -> int: ...
  def ChannelNumber(self) -> int: ...
  def Ranges(self, i: int) -> PowerRange | None: ...
  def RangesLength(self) -> int: ...
  def RangesIsNone(self) -> bool: ...
  def MeasurementMode(self) -> typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]: ...
  def MonitorMode(self) -> typing.Literal[PowerMonitorMode.Unknown, PowerMonitorMode.TSLMonitor, PowerMonitorMode.MPMChannel, PowerMonitorMode.SPUMonitor]: ...
def STPLoggingParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def STPLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int) -> None: ...
def STPLoggingParametersAddChannelNumber(builder: flatbuffers.Builder, channelNumber: int) -> None: ...
def STPLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: uoffset) -> None: ...
def STPLoggingParametersStartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartRangesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def STPLoggingParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]) -> None: ...
def STPLoggingParametersAddMonitorMode(builder: flatbuffers.Builder, monitorMode: typing.Literal[PowerMonitorMode.Unknown, PowerMonitorMode.TSLMonitor, PowerMonitorMode.MPMChannel, PowerMonitorMode.SPUMonitor]) -> None: ...
def STPLoggingParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

