# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Parameters.PowerRange import PowerRange
from typing import Optional
np = import_numpy()

class STPLoggingParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = STPLoggingParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSTPLoggingParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # STPLoggingParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # STPLoggingParameters
    def ModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # STPLoggingParameters
    def ChannelNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # STPLoggingParameters
    def Ranges(self, j: int) -> Optional[PowerRange]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = PowerRange()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # STPLoggingParameters
    def RangesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # STPLoggingParameters
    def RangesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # STPLoggingParameters
    def MeasurementMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # STPLoggingParameters
    def MonitorMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def STPLoggingParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    STPLoggingParametersStart(builder)

def STPLoggingParametersAddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    builder.PrependInt32Slot(0, moduleNumber, 0)

def AddModuleNumber(builder: flatbuffers.Builder, moduleNumber: int):
    STPLoggingParametersAddModuleNumber(builder, moduleNumber)

def STPLoggingParametersAddChannelNumber(builder: flatbuffers.Builder, channelNumber: int):
    builder.PrependInt32Slot(1, channelNumber, 0)

def AddChannelNumber(builder: flatbuffers.Builder, channelNumber: int):
    STPLoggingParametersAddChannelNumber(builder, channelNumber)

def STPLoggingParametersAddRanges(builder: flatbuffers.Builder, ranges: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ranges), 0)

def AddRanges(builder: flatbuffers.Builder, ranges: int):
    STPLoggingParametersAddRanges(builder, ranges)

def STPLoggingParametersStartRangesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRangesVector(builder, numElems: int) -> int:
    return STPLoggingParametersStartRangesVector(builder, numElems)

def STPLoggingParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    builder.PrependInt8Slot(3, measurementMode, 0)

def AddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    STPLoggingParametersAddMeasurementMode(builder, measurementMode)

def STPLoggingParametersAddMonitorMode(builder: flatbuffers.Builder, monitorMode: int):
    builder.PrependInt8Slot(4, monitorMode, 0)

def AddMonitorMode(builder: flatbuffers.Builder, monitorMode: int):
    STPLoggingParametersAddMonitorMode(builder, monitorMode)

def STPLoggingParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return STPLoggingParametersEnd(builder)
