from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.STP.MeasurementMode import MeasurementMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class STPParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> STPParameters: ...
  @classmethod
  def GetRootAsSTPParameters(cls, buf: bytes, offset: int) -> STPParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MeasurementMode(self) -> typing.Literal[MeasurementMode.ManualRangeConstant, MeasurementMode.ManualRangeSweep, MeasurementMode.AutoRangeConstant, MeasurementMode.AutoRangeSweep, MeasurementMode.FreeRun]: ...
  def HighSpecMode(self) -> bool: ...
  def Start(self) -> float: ...
  def Stop(self) -> float: ...
  def Step(self) -> float: ...
  def Speed(self) -> float: ...
  def ReturnLossMode(self) -> bool: ...
  def ReturnLossModuleNumber(self) -> int: ...
  def ReturnLossChannelNumber(self) -> int: ...
def STPParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def STPParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: typing.Literal[MeasurementMode.ManualRangeConstant, MeasurementMode.ManualRangeSweep, MeasurementMode.AutoRangeConstant, MeasurementMode.AutoRangeSweep, MeasurementMode.FreeRun]) -> None: ...
def STPParametersAddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool) -> None: ...
def STPParametersAddStart(builder: flatbuffers.Builder, start: float) -> None: ...
def STPParametersAddStop(builder: flatbuffers.Builder, stop: float) -> None: ...
def STPParametersAddStep(builder: flatbuffers.Builder, step: float) -> None: ...
def STPParametersAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def STPParametersAddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool) -> None: ...
def STPParametersAddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int) -> None: ...
def STPParametersAddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int) -> None: ...
def STPParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

