# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class STPParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = STPParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSTPParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # STPParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # STPParameters
    def MeasurementMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # STPParameters
    def HighSpecMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # STPParameters
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # STPParameters
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # STPParameters
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # STPParameters
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # STPParameters
    def ReturnLossMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # STPParameters
    def ReturnLossModuleNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # STPParameters
    def ReturnLossChannelNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def STPParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    STPParametersStart(builder)

def STPParametersAddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    builder.PrependInt8Slot(0, measurementMode, 0)

def AddMeasurementMode(builder: flatbuffers.Builder, measurementMode: int):
    STPParametersAddMeasurementMode(builder, measurementMode)

def STPParametersAddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool):
    builder.PrependBoolSlot(1, highSpecMode, 0)

def AddHighSpecMode(builder: flatbuffers.Builder, highSpecMode: bool):
    STPParametersAddHighSpecMode(builder, highSpecMode)

def STPParametersAddStart(builder: flatbuffers.Builder, start: float):
    builder.PrependFloat64Slot(2, start, 0.0)

def AddStart(builder: flatbuffers.Builder, start: float):
    STPParametersAddStart(builder, start)

def STPParametersAddStop(builder: flatbuffers.Builder, stop: float):
    builder.PrependFloat64Slot(3, stop, 0.0)

def AddStop(builder: flatbuffers.Builder, stop: float):
    STPParametersAddStop(builder, stop)

def STPParametersAddStep(builder: flatbuffers.Builder, step: float):
    builder.PrependFloat64Slot(4, step, 0.0)

def AddStep(builder: flatbuffers.Builder, step: float):
    STPParametersAddStep(builder, step)

def STPParametersAddSpeed(builder: flatbuffers.Builder, speed: float):
    builder.PrependFloat64Slot(5, speed, 0.0)

def AddSpeed(builder: flatbuffers.Builder, speed: float):
    STPParametersAddSpeed(builder, speed)

def STPParametersAddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool):
    builder.PrependBoolSlot(6, returnLossMode, 0)

def AddReturnLossMode(builder: flatbuffers.Builder, returnLossMode: bool):
    STPParametersAddReturnLossMode(builder, returnLossMode)

def STPParametersAddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int):
    builder.PrependInt32Slot(7, returnLossModuleNumber, 0)

def AddReturnLossModuleNumber(builder: flatbuffers.Builder, returnLossModuleNumber: int):
    STPParametersAddReturnLossModuleNumber(builder, returnLossModuleNumber)

def STPParametersAddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int):
    builder.PrependInt32Slot(8, returnLossChannelNumber, 0)

def AddReturnLossChannelNumber(builder: flatbuffers.Builder, returnLossChannelNumber: int):
    STPParametersAddReturnLossChannelNumber(builder, returnLossChannelNumber)

def STPParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return STPParametersEnd(builder)
