from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.TSL.AmplitudeModulationSource import AmplitudeModulationSource
from Santec.Instruments.Native.Enums.TSL.AmplitudeModulationStatus import AmplitudeModulationStatus
from Santec.Instruments.Native.Enums.TSL.PowerMode import PowerMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TSLMainParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TSLMainParameters: ...
  @classmethod
  def GetRootAsTSLMainParameters(cls, buf: bytes, offset: int) -> TSLMainParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Wavelength(self) -> float: ...
  def WavelengthUnit(self) -> int: ...
  def FineTuning(self) -> float: ...
  def Power(self) -> float: ...
  def PowerUnit(self) -> int: ...
  def Attenuator(self) -> float: ...
  def FineTuningEnabled(self) -> bool: ...
  def PowerMode(self) -> typing.Literal[PowerMode.Manual, PowerMode.Auto]: ...
  def ModulationState(self) -> typing.Literal[AmplitudeModulationStatus.Disable, AmplitudeModulationStatus.Enable]: ...
  def ModulationSource(self) -> typing.Literal[AmplitudeModulationSource.CoherenceControl, AmplitudeModulationSource.IntensityModulation, AmplitudeModulationSource.FrequencyModulation]: ...
def TSLMainParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TSLMainParametersAddWavelength(builder: flatbuffers.Builder, wavelength: float) -> None: ...
def TSLMainParametersAddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int) -> None: ...
def TSLMainParametersAddFineTuning(builder: flatbuffers.Builder, fineTuning: float) -> None: ...
def TSLMainParametersAddPower(builder: flatbuffers.Builder, power: float) -> None: ...
def TSLMainParametersAddPowerUnit(builder: flatbuffers.Builder, powerUnit: int) -> None: ...
def TSLMainParametersAddAttenuator(builder: flatbuffers.Builder, attenuator: float) -> None: ...
def TSLMainParametersAddFineTuningEnabled(builder: flatbuffers.Builder, fineTuningEnabled: bool) -> None: ...
def TSLMainParametersAddPowerMode(builder: flatbuffers.Builder, powerMode: typing.Literal[PowerMode.Manual, PowerMode.Auto]) -> None: ...
def TSLMainParametersAddModulationState(builder: flatbuffers.Builder, modulationState: typing.Literal[AmplitudeModulationStatus.Disable, AmplitudeModulationStatus.Enable]) -> None: ...
def TSLMainParametersAddModulationSource(builder: flatbuffers.Builder, modulationSource: typing.Literal[AmplitudeModulationSource.CoherenceControl, AmplitudeModulationSource.IntensityModulation, AmplitudeModulationSource.FrequencyModulation]) -> None: ...
def TSLMainParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

