# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class TSLMainParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TSLMainParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTSLMainParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TSLMainParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TSLMainParameters
    def Wavelength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLMainParameters
    def WavelengthUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TSLMainParameters
    def FineTuning(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLMainParameters
    def Power(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLMainParameters
    def PowerUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TSLMainParameters
    def Attenuator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLMainParameters
    def FineTuningEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TSLMainParameters
    def PowerMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLMainParameters
    def ModulationState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLMainParameters
    def ModulationSource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TSLMainParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(10)

def Start(builder: flatbuffers.Builder):
    TSLMainParametersStart(builder)

def TSLMainParametersAddWavelength(builder: flatbuffers.Builder, wavelength: float):
    builder.PrependFloat64Slot(0, wavelength, 0.0)

def AddWavelength(builder: flatbuffers.Builder, wavelength: float):
    TSLMainParametersAddWavelength(builder, wavelength)

def TSLMainParametersAddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int):
    builder.PrependInt32Slot(1, wavelengthUnit, 0)

def AddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int):
    TSLMainParametersAddWavelengthUnit(builder, wavelengthUnit)

def TSLMainParametersAddFineTuning(builder: flatbuffers.Builder, fineTuning: float):
    builder.PrependFloat64Slot(2, fineTuning, 0.0)

def AddFineTuning(builder: flatbuffers.Builder, fineTuning: float):
    TSLMainParametersAddFineTuning(builder, fineTuning)

def TSLMainParametersAddPower(builder: flatbuffers.Builder, power: float):
    builder.PrependFloat64Slot(3, power, 0.0)

def AddPower(builder: flatbuffers.Builder, power: float):
    TSLMainParametersAddPower(builder, power)

def TSLMainParametersAddPowerUnit(builder: flatbuffers.Builder, powerUnit: int):
    builder.PrependInt32Slot(4, powerUnit, 0)

def AddPowerUnit(builder: flatbuffers.Builder, powerUnit: int):
    TSLMainParametersAddPowerUnit(builder, powerUnit)

def TSLMainParametersAddAttenuator(builder: flatbuffers.Builder, attenuator: float):
    builder.PrependFloat64Slot(5, attenuator, 0.0)

def AddAttenuator(builder: flatbuffers.Builder, attenuator: float):
    TSLMainParametersAddAttenuator(builder, attenuator)

def TSLMainParametersAddFineTuningEnabled(builder: flatbuffers.Builder, fineTuningEnabled: bool):
    builder.PrependBoolSlot(6, fineTuningEnabled, 0)

def AddFineTuningEnabled(builder: flatbuffers.Builder, fineTuningEnabled: bool):
    TSLMainParametersAddFineTuningEnabled(builder, fineTuningEnabled)

def TSLMainParametersAddPowerMode(builder: flatbuffers.Builder, powerMode: int):
    builder.PrependInt8Slot(7, powerMode, 0)

def AddPowerMode(builder: flatbuffers.Builder, powerMode: int):
    TSLMainParametersAddPowerMode(builder, powerMode)

def TSLMainParametersAddModulationState(builder: flatbuffers.Builder, modulationState: int):
    builder.PrependInt8Slot(8, modulationState, 0)

def AddModulationState(builder: flatbuffers.Builder, modulationState: int):
    TSLMainParametersAddModulationState(builder, modulationState)

def TSLMainParametersAddModulationSource(builder: flatbuffers.Builder, modulationSource: int):
    builder.PrependInt8Slot(9, modulationSource, 0)

def AddModulationSource(builder: flatbuffers.Builder, modulationSource: int):
    TSLMainParametersAddModulationSource(builder, modulationSource)

def TSLMainParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TSLMainParametersEnd(builder)
