from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.TSL.SweepMode import SweepMode

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TSLSweepParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TSLSweepParameters: ...
  @classmethod
  def GetRootAsTSLSweepParameters(cls, buf: bytes, offset: int) -> TSLSweepParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SweepMode(self) -> typing.Literal[SweepMode.ContinuousOneWay, SweepMode.StepOneWay, SweepMode.ContinuousTwoWay, SweepMode.StepTwoWay]: ...
  def Start(self) -> float: ...
  def Stop(self) -> float: ...
  def WavelengthUnit(self) -> int: ...
  def Speed(self) -> float: ...
  def Cycles(self) -> int: ...
  def Delay(self) -> float: ...
  def StepWidth(self) -> float: ...
  def HighResolution(self) -> bool: ...
def TSLSweepParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TSLSweepParametersAddSweepMode(builder: flatbuffers.Builder, sweepMode: typing.Literal[SweepMode.ContinuousOneWay, SweepMode.StepOneWay, SweepMode.ContinuousTwoWay, SweepMode.StepTwoWay]) -> None: ...
def TSLSweepParametersAddStart(builder: flatbuffers.Builder, start: float) -> None: ...
def TSLSweepParametersAddStop(builder: flatbuffers.Builder, stop: float) -> None: ...
def TSLSweepParametersAddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int) -> None: ...
def TSLSweepParametersAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def TSLSweepParametersAddCycles(builder: flatbuffers.Builder, cycles: int) -> None: ...
def TSLSweepParametersAddDelay(builder: flatbuffers.Builder, delay: float) -> None: ...
def TSLSweepParametersAddStepWidth(builder: flatbuffers.Builder, stepWidth: float) -> None: ...
def TSLSweepParametersAddHighResolution(builder: flatbuffers.Builder, highResolution: bool) -> None: ...
def TSLSweepParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

