# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class TSLSweepParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TSLSweepParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTSLSweepParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TSLSweepParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TSLSweepParameters
    def SweepMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLSweepParameters
    def Start(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLSweepParameters
    def Stop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLSweepParameters
    def WavelengthUnit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TSLSweepParameters
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLSweepParameters
    def Cycles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TSLSweepParameters
    def Delay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLSweepParameters
    def StepWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TSLSweepParameters
    def HighResolution(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TSLSweepParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    TSLSweepParametersStart(builder)

def TSLSweepParametersAddSweepMode(builder: flatbuffers.Builder, sweepMode: int):
    builder.PrependInt8Slot(0, sweepMode, 0)

def AddSweepMode(builder: flatbuffers.Builder, sweepMode: int):
    TSLSweepParametersAddSweepMode(builder, sweepMode)

def TSLSweepParametersAddStart(builder: flatbuffers.Builder, start: float):
    builder.PrependFloat64Slot(1, start, 0.0)

def AddStart(builder: flatbuffers.Builder, start: float):
    TSLSweepParametersAddStart(builder, start)

def TSLSweepParametersAddStop(builder: flatbuffers.Builder, stop: float):
    builder.PrependFloat64Slot(2, stop, 0.0)

def AddStop(builder: flatbuffers.Builder, stop: float):
    TSLSweepParametersAddStop(builder, stop)

def TSLSweepParametersAddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int):
    builder.PrependInt32Slot(3, wavelengthUnit, 0)

def AddWavelengthUnit(builder: flatbuffers.Builder, wavelengthUnit: int):
    TSLSweepParametersAddWavelengthUnit(builder, wavelengthUnit)

def TSLSweepParametersAddSpeed(builder: flatbuffers.Builder, speed: float):
    builder.PrependFloat64Slot(4, speed, 0.0)

def AddSpeed(builder: flatbuffers.Builder, speed: float):
    TSLSweepParametersAddSpeed(builder, speed)

def TSLSweepParametersAddCycles(builder: flatbuffers.Builder, cycles: int):
    builder.PrependInt32Slot(5, cycles, 0)

def AddCycles(builder: flatbuffers.Builder, cycles: int):
    TSLSweepParametersAddCycles(builder, cycles)

def TSLSweepParametersAddDelay(builder: flatbuffers.Builder, delay: float):
    builder.PrependFloat64Slot(6, delay, 0.0)

def AddDelay(builder: flatbuffers.Builder, delay: float):
    TSLSweepParametersAddDelay(builder, delay)

def TSLSweepParametersAddStepWidth(builder: flatbuffers.Builder, stepWidth: float):
    builder.PrependFloat64Slot(7, stepWidth, 0.0)

def AddStepWidth(builder: flatbuffers.Builder, stepWidth: float):
    TSLSweepParametersAddStepWidth(builder, stepWidth)

def TSLSweepParametersAddHighResolution(builder: flatbuffers.Builder, highResolution: bool):
    builder.PrependBoolSlot(8, highResolution, 0)

def AddHighResolution(builder: flatbuffers.Builder, highResolution: bool):
    TSLSweepParametersAddHighResolution(builder, highResolution)

def TSLSweepParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TSLSweepParametersEnd(builder)
