# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Parameters

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class TSLTriggerParameters(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TSLTriggerParameters()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTSLTriggerParameters(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TSLTriggerParameters
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TSLTriggerParameters
    def StartTrigger(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLTriggerParameters
    def ConstantMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLTriggerParameters
    def TimingMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLTriggerParameters
    def InputPolarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLTriggerParameters
    def OutputPolarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TSLTriggerParameters
    def PassThrough(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TSLTriggerParameters
    def RearBnc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TSLTriggerParametersStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    TSLTriggerParametersStart(builder)

def TSLTriggerParametersAddStartTrigger(builder: flatbuffers.Builder, startTrigger: int):
    builder.PrependInt8Slot(0, startTrigger, 0)

def AddStartTrigger(builder: flatbuffers.Builder, startTrigger: int):
    TSLTriggerParametersAddStartTrigger(builder, startTrigger)

def TSLTriggerParametersAddConstantMode(builder: flatbuffers.Builder, constantMode: int):
    builder.PrependInt8Slot(1, constantMode, 0)

def AddConstantMode(builder: flatbuffers.Builder, constantMode: int):
    TSLTriggerParametersAddConstantMode(builder, constantMode)

def TSLTriggerParametersAddTimingMode(builder: flatbuffers.Builder, timingMode: int):
    builder.PrependInt8Slot(2, timingMode, 0)

def AddTimingMode(builder: flatbuffers.Builder, timingMode: int):
    TSLTriggerParametersAddTimingMode(builder, timingMode)

def TSLTriggerParametersAddInputPolarity(builder: flatbuffers.Builder, inputPolarity: int):
    builder.PrependInt8Slot(3, inputPolarity, 0)

def AddInputPolarity(builder: flatbuffers.Builder, inputPolarity: int):
    TSLTriggerParametersAddInputPolarity(builder, inputPolarity)

def TSLTriggerParametersAddOutputPolarity(builder: flatbuffers.Builder, outputPolarity: int):
    builder.PrependInt8Slot(4, outputPolarity, 0)

def AddOutputPolarity(builder: flatbuffers.Builder, outputPolarity: int):
    TSLTriggerParametersAddOutputPolarity(builder, outputPolarity)

def TSLTriggerParametersAddPassThrough(builder: flatbuffers.Builder, passThrough: bool):
    builder.PrependBoolSlot(5, passThrough, 0)

def AddPassThrough(builder: flatbuffers.Builder, passThrough: bool):
    TSLTriggerParametersAddPassThrough(builder, passThrough)

def TSLTriggerParametersAddRearBnc(builder: flatbuffers.Builder, rearBnc: int):
    builder.PrependInt8Slot(6, rearBnc, 0)

def AddRearBnc(builder: flatbuffers.Builder, rearBnc: int):
    TSLTriggerParametersAddRearBnc(builder, rearBnc)

def TSLTriggerParametersEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return TSLTriggerParametersEnd(builder)
