from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.Instruments.Native.Enums.TSL.InputTriggerPolarity import InputTriggerPolarity
from Santec.Instruments.Native.Enums.TSL.OutputTriggerPolarity import OutputTriggerPolarity
from Santec.Instruments.Native.Enums.TSL.SweepStartMode import SweepStartMode
from Santec.Instruments.Native.Enums.TSL.TriggerInputMode import TriggerInputMode
from Santec.Instruments.Native.Enums.TSL.TriggerOutputMode import TriggerOutputMode
from Santec.Instruments.Native.Enums.TSL.TriggerOutputSource import TriggerOutputSource

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class TSLTriggerParameters(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> TSLTriggerParameters: ...
  @classmethod
  def GetRootAsTSLTriggerParameters(cls, buf: bytes, offset: int) -> TSLTriggerParameters: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def StartTrigger(self) -> typing.Literal[SweepStartMode.Auto, SweepStartMode.WaitingForTrigger]: ...
  def ConstantMode(self) -> typing.Literal[TriggerOutputSource.Wavelength, TriggerOutputSource.Time]: ...
  def TimingMode(self) -> typing.Literal[TriggerOutputMode.None_, TriggerOutputMode.Stop, TriggerOutputMode.Start, TriggerOutputMode.Step]: ...
  def InputPolarity(self) -> typing.Literal[InputTriggerPolarity.HighActive, InputTriggerPolarity.LowActive]: ...
  def OutputPolarity(self) -> typing.Literal[OutputTriggerPolarity.HighActive, OutputTriggerPolarity.LowActive]: ...
  def PassThrough(self) -> bool: ...
  def RearBnc(self) -> typing.Literal[TriggerInputMode.Disable, TriggerInputMode.Enable]: ...
def TSLTriggerParametersStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TSLTriggerParametersAddStartTrigger(builder: flatbuffers.Builder, startTrigger: typing.Literal[SweepStartMode.Auto, SweepStartMode.WaitingForTrigger]) -> None: ...
def TSLTriggerParametersAddConstantMode(builder: flatbuffers.Builder, constantMode: typing.Literal[TriggerOutputSource.Wavelength, TriggerOutputSource.Time]) -> None: ...
def TSLTriggerParametersAddTimingMode(builder: flatbuffers.Builder, timingMode: typing.Literal[TriggerOutputMode.None_, TriggerOutputMode.Stop, TriggerOutputMode.Start, TriggerOutputMode.Step]) -> None: ...
def TSLTriggerParametersAddInputPolarity(builder: flatbuffers.Builder, inputPolarity: typing.Literal[InputTriggerPolarity.HighActive, InputTriggerPolarity.LowActive]) -> None: ...
def TSLTriggerParametersAddOutputPolarity(builder: flatbuffers.Builder, outputPolarity: typing.Literal[OutputTriggerPolarity.HighActive, OutputTriggerPolarity.LowActive]) -> None: ...
def TSLTriggerParametersAddPassThrough(builder: flatbuffers.Builder, passThrough: bool) -> None: ...
def TSLTriggerParametersAddRearBnc(builder: flatbuffers.Builder, rearBnc: typing.Literal[TriggerInputMode.Disable, TriggerInputMode.Enable]) -> None: ...
def TSLTriggerParametersEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

