from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Rescale.RescaledScanDataSetEntry import RescaledScanDataSetEntry

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RescaledScanDataSet(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaledScanDataSet: ...
  @classmethod
  def GetRootAsRescaledScanDataSet(cls, buf: bytes, offset: int) -> RescaledScanDataSet: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> RescaledScanDataSetEntry | None: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
def RescaledScanDataSetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RescaledScanDataSetAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RescaledScanDataSetStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RescaledScanDataSetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

