# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Rescale

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class RescaledPowerLog(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RescaledPowerLog()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRescaledPowerLog(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RescaledPowerLog
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RescaledPowerLog
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RescaledPowerLog
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # RescaledPowerLog
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RescaledPowerLog
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RescaledPowerLog
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def RescaledPowerLogStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    RescaledPowerLogStart(builder)

def RescaledPowerLogAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RescaledPowerLogAddData(builder, data)

def RescaledPowerLogStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return RescaledPowerLogStartDataVector(builder, numElems)

def RescaledPowerLogAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependInt32Slot(1, unit, 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    RescaledPowerLogAddUnit(builder, unit)

def RescaledPowerLogEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RescaledPowerLogEnd(builder)
