from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RescaledPowerMonitorLog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaledPowerMonitorLog: ...
  @classmethod
  def GetRootAsRescaledPowerMonitorLog(cls, buf: bytes, offset: int) -> RescaledPowerMonitorLog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Unit(self) -> int: ...
def RescaledPowerMonitorLogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RescaledPowerMonitorLogAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RescaledPowerMonitorLogStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RescaledPowerMonitorLogAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def RescaledPowerMonitorLogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

