# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Rescale

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Rescale.RescaledTriggerLog import RescaledTriggerLog
from typing import Optional
np = import_numpy()

class RescaledTriggerData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RescaledTriggerData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRescaledTriggerData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RescaledTriggerData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RescaledTriggerData
    def PowerTriggerLog(self) -> Optional[RescaledTriggerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RescaledTriggerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RescaledTriggerData
    def PowerMonitorTriggerLog(self) -> Optional[RescaledTriggerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RescaledTriggerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RescaledTriggerDataStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    RescaledTriggerDataStart(builder)

def RescaledTriggerDataAddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(powerTriggerLog), 0)

def AddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: int):
    RescaledTriggerDataAddPowerTriggerLog(builder, powerTriggerLog)

def RescaledTriggerDataAddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(powerMonitorTriggerLog), 0)

def AddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: int):
    RescaledTriggerDataAddPowerMonitorTriggerLog(builder, powerMonitorTriggerLog)

def RescaledTriggerDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RescaledTriggerDataEnd(builder)
