from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Rescale.RescaledScanData import RescaledScanData
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RescaledScanDataSetEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaledScanDataSetEntry: ...
  @classmethod
  def GetRootAsRescaledScanDataSetEntry(cls, buf: bytes, offset: int) -> RescaledScanDataSetEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> RawDataKey | None: ...
  def Data(self) -> RescaledScanData | None: ...
def RescaledScanDataSetEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RescaledScanDataSetEntryAddKey(builder: flatbuffers.Builder, key: uoffset) -> None: ...
def RescaledScanDataSetEntryAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RescaledScanDataSetEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

