# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Rescale

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Rescale.RescaledScanData import RescaledScanData
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from typing import Optional
np = import_numpy()

class RescaledScanDataSetEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RescaledScanDataSetEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRescaledScanDataSetEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RescaledScanDataSetEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RescaledScanDataSetEntry
    def Key(self) -> Optional[RawDataKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawDataKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RescaledScanDataSetEntry
    def Data(self) -> Optional[RescaledScanData]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RescaledScanData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RescaledScanDataSetEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    RescaledScanDataSetEntryStart(builder)

def RescaledScanDataSetEntryAddKey(builder: flatbuffers.Builder, key: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder: flatbuffers.Builder, key: int):
    RescaledScanDataSetEntryAddKey(builder, key)

def RescaledScanDataSetEntryAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RescaledScanDataSetEntryAddData(builder, data)

def RescaledScanDataSetEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RescaledScanDataSetEntryEnd(builder)
