from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Rescale.RescaledPowerLog import RescaledPowerLog
from Santec.STSProcess.Process.Native.Rescale.RescaledPowerMonitorLog import RescaledPowerMonitorLog
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from Santec.STSProcess.Process.Native.Result.SweepInfo import SweepInfo

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RescaledScanData(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaledScanData: ...
  @classmethod
  def GetRootAsRescaledScanData(cls, buf: bytes, offset: int) -> RescaledScanData: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> RawDataKey | None: ...
  def SweepData(self) -> SweepInfo | None: ...
  def PowerLog(self) -> RescaledPowerLog | None: ...
  def PowerMonitorLog(self) -> RescaledPowerMonitorLog | None: ...
def RescaledScanDataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RescaledScanDataAddKey(builder: flatbuffers.Builder, key: uoffset) -> None: ...
def RescaledScanDataAddSweepData(builder: flatbuffers.Builder, sweepData: uoffset) -> None: ...
def RescaledScanDataAddPowerLog(builder: flatbuffers.Builder, powerLog: uoffset) -> None: ...
def RescaledScanDataAddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: uoffset) -> None: ...
def RescaledScanDataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

