# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Rescale

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Rescale.RescaledPowerLog import RescaledPowerLog
from Santec.STSProcess.Process.Native.Rescale.RescaledPowerMonitorLog import RescaledPowerMonitorLog
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from Santec.STSProcess.Process.Native.Result.SweepInfo import SweepInfo
from typing import Optional
np = import_numpy()

class RescaledScanData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RescaledScanData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRescaledScanData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RescaledScanData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RescaledScanData
    def Key(self) -> Optional[RawDataKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawDataKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RescaledScanData
    def SweepData(self) -> Optional[SweepInfo]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SweepInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RescaledScanData
    def PowerLog(self) -> Optional[RescaledPowerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RescaledPowerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RescaledScanData
    def PowerMonitorLog(self) -> Optional[RescaledPowerMonitorLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RescaledPowerMonitorLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RescaledScanDataStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    RescaledScanDataStart(builder)

def RescaledScanDataAddKey(builder: flatbuffers.Builder, key: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder: flatbuffers.Builder, key: int):
    RescaledScanDataAddKey(builder, key)

def RescaledScanDataAddSweepData(builder: flatbuffers.Builder, sweepData: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sweepData), 0)

def AddSweepData(builder: flatbuffers.Builder, sweepData: int):
    RescaledScanDataAddSweepData(builder, sweepData)

def RescaledScanDataAddPowerLog(builder: flatbuffers.Builder, powerLog: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(powerLog), 0)

def AddPowerLog(builder: flatbuffers.Builder, powerLog: int):
    RescaledScanDataAddPowerLog(builder, powerLog)

def RescaledScanDataAddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(powerMonitorLog), 0)

def AddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: int):
    RescaledScanDataAddPowerMonitorLog(builder, powerMonitorLog)

def RescaledScanDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RescaledScanDataEnd(builder)
