from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Rescale.RescaledTriggerLog import RescaledTriggerLog

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RescaledTriggerData(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RescaledTriggerData: ...
  @classmethod
  def GetRootAsRescaledTriggerData(cls, buf: bytes, offset: int) -> RescaledTriggerData: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PowerTriggerLog(self) -> RescaledTriggerLog | None: ...
  def PowerMonitorTriggerLog(self) -> RescaledTriggerLog | None: ...
def RescaledTriggerDataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RescaledTriggerDataAddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: uoffset) -> None: ...
def RescaledTriggerDataAddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: uoffset) -> None: ...
def RescaledTriggerDataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

