# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TSL

class AmplitudeModulationSource(object):
    CoherenceControl = 0
    IntensityModulation = 1
    FrequencyModulation = 2
