# automatically generated by the FlatBuffers compiler, do not modify

# namespace: TSL

class SweepMode(object):
    ContinuousOneWay = 0
    StepOneWay = 1
    ContinuousTwoWay = 2
    StepTwoWay = 3
