# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

class MeasurementMode(object):
    Unknown = 0
    SPUFreerun = 1
    MPMFreerun = 2
    SingleMeasurement = 3
