# automatically generated by the FlatBuffers compiler, do not modify

# namespace: STP

class MeasurementMode(object):
    ManualRangeConstant = 0
    ManualRangeSweep = 1
    AutoRangeConstant = 2
    AutoRangeSweep = 3
    FreeRun = 4
