# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Raw

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class RawPowerMonitorLog(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RawPowerMonitorLog()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRawPowerMonitorLog(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RawPowerMonitorLog
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RawPowerMonitorLog
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RawPowerMonitorLog
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # RawPowerMonitorLog
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RawPowerMonitorLog
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RawPowerMonitorLog
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RawPowerMonitorLog
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def RawPowerMonitorLogStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    RawPowerMonitorLogStart(builder)

def RawPowerMonitorLogAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RawPowerMonitorLogAddData(builder, data)

def RawPowerMonitorLogStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return RawPowerMonitorLogStartDataVector(builder, numElems)

def RawPowerMonitorLogAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependInt32Slot(1, unit, 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    RawPowerMonitorLogAddUnit(builder, unit)

def RawPowerMonitorLogAddSource(builder: flatbuffers.Builder, source: int):
    builder.PrependInt8Slot(2, source, 0)

def AddSource(builder: flatbuffers.Builder, source: int):
    RawPowerMonitorLogAddSource(builder, source)

def RawPowerMonitorLogEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RawPowerMonitorLogEnd(builder)
