# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Raw

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class RawPowerLog(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RawPowerLog()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRawPowerLog(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RawPowerLog
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RawPowerLog
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RawPowerLog
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # RawPowerLog
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RawPowerLog
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # RawPowerLog
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RawPowerLog
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RawPowerLog
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def RawPowerLogStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    RawPowerLogStart(builder)

def RawPowerLogAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RawPowerLogAddData(builder, data)

def RawPowerLogStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return RawPowerLogStartDataVector(builder, numElems)

def RawPowerLogAddUnit(builder: flatbuffers.Builder, unit: int):
    builder.PrependInt32Slot(1, unit, 0)

def AddUnit(builder: flatbuffers.Builder, unit: int):
    RawPowerLogAddUnit(builder, unit)

def RawPowerLogAddSource(builder: flatbuffers.Builder, source: int):
    builder.PrependInt8Slot(2, source, 0)

def AddSource(builder: flatbuffers.Builder, source: int):
    RawPowerLogAddSource(builder, source)

def RawPowerLogAddMode(builder: flatbuffers.Builder, mode: int):
    builder.PrependInt8Slot(3, mode, 0)

def AddMode(builder: flatbuffers.Builder, mode: int):
    RawPowerLogAddMode(builder, mode)

def RawPowerLogEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RawPowerLogEnd(builder)
