from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.MeasurementMode import MeasurementMode
from Santec.STSProcess.Process.Native.Common.PowerLogSource import PowerLogSource

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawPowerLog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawPowerLog: ...
  @classmethod
  def GetRootAsRawPowerLog(cls, buf: bytes, offset: int) -> RawPowerLog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Unit(self) -> int: ...
  def Source(self) -> typing.Literal[PowerLogSource.Unknown, PowerLogSource.MPM, PowerLogSource.OPM, PowerLogSource.LMS]: ...
  def Mode(self) -> typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]: ...
def RawPowerLogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawPowerLogAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawPowerLogStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RawPowerLogAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def RawPowerLogAddSource(builder: flatbuffers.Builder, source: typing.Literal[PowerLogSource.Unknown, PowerLogSource.MPM, PowerLogSource.OPM, PowerLogSource.LMS]) -> None: ...
def RawPowerLogAddMode(builder: flatbuffers.Builder, mode: typing.Literal[MeasurementMode.Unknown, MeasurementMode.SPUFreerun, MeasurementMode.MPMFreerun, MeasurementMode.SingleMeasurement]) -> None: ...
def RawPowerLogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

