from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.PowerMonitorLogSource import PowerMonitorLogSource

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawPowerMonitorLog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawPowerMonitorLog: ...
  @classmethod
  def GetRootAsRawPowerMonitorLog(cls, buf: bytes, offset: int) -> RawPowerMonitorLog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Unit(self) -> int: ...
  def Source(self) -> typing.Literal[PowerMonitorLogSource.Unknown, PowerMonitorLogSource.TSL, PowerMonitorLogSource.SPU, PowerMonitorLogSource.MPM]: ...
def RawPowerMonitorLogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawPowerMonitorLogAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawPowerMonitorLogStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RawPowerMonitorLogAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def RawPowerMonitorLogAddSource(builder: flatbuffers.Builder, source: typing.Literal[PowerMonitorLogSource.Unknown, PowerMonitorLogSource.TSL, PowerMonitorLogSource.SPU, PowerMonitorLogSource.MPM]) -> None: ...
def RawPowerMonitorLogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

