from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Raw.RawScanDataSetEntry import RawScanDataSetEntry

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawScanDataSet(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawScanDataSet: ...
  @classmethod
  def GetRootAsRawScanDataSet(cls, buf: bytes, offset: int) -> RawScanDataSet: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> RawScanDataSetEntry | None: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
def RawScanDataSetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawScanDataSetAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawScanDataSetStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RawScanDataSetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

