from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Raw.RawScanData import RawScanData
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawScanDataSetEntry(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawScanDataSetEntry: ...
  @classmethod
  def GetRootAsRawScanDataSetEntry(cls, buf: bytes, offset: int) -> RawScanDataSetEntry: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> RawDataKey | None: ...
  def Data(self) -> RawScanData | None: ...
def RawScanDataSetEntryStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawScanDataSetEntryAddKey(builder: flatbuffers.Builder, key: uoffset) -> None: ...
def RawScanDataSetEntryAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawScanDataSetEntryEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

