# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Raw

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Raw.RawScanDataSetEntry import RawScanDataSetEntry
from typing import Optional
np = import_numpy()

class RawScanDataSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RawScanDataSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRawScanDataSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RawScanDataSet
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RawScanDataSet
    def Data(self, j: int) -> Optional[RawScanDataSetEntry]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = RawScanDataSetEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanDataSet
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RawScanDataSet
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def RawScanDataSetStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    RawScanDataSetStart(builder)

def RawScanDataSetAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RawScanDataSetAddData(builder, data)

def RawScanDataSetStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems: int) -> int:
    return RawScanDataSetStartDataVector(builder, numElems)

def RawScanDataSetEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RawScanDataSetEnd(builder)
