from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Raw.RawPowerLog import RawPowerLog
from Santec.STSProcess.Process.Native.Raw.RawPowerMonitorLog import RawPowerMonitorLog
from Santec.STSProcess.Process.Native.Raw.RawTriggerLog import RawTriggerLog
from Santec.STSProcess.Process.Native.Raw.RawWavelengthLog import RawWavelengthLog
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from Santec.STSProcess.Process.Native.Result.SweepInfo import SweepInfo

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawScanData(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawScanData: ...
  @classmethod
  def GetRootAsRawScanData(cls, buf: bytes, offset: int) -> RawScanData: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> RawDataKey | None: ...
  def SweepData(self) -> SweepInfo | None: ...
  def PowerLog(self) -> RawPowerLog | None: ...
  def PowerTriggerLog(self) -> RawTriggerLog | None: ...
  def PowerMonitorLog(self) -> RawPowerMonitorLog | None: ...
  def PowerMonitorTriggerLog(self) -> RawTriggerLog | None: ...
  def WavelengthLog(self) -> RawWavelengthLog | None: ...
def RawScanDataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawScanDataAddKey(builder: flatbuffers.Builder, key: uoffset) -> None: ...
def RawScanDataAddSweepData(builder: flatbuffers.Builder, sweepData: uoffset) -> None: ...
def RawScanDataAddPowerLog(builder: flatbuffers.Builder, powerLog: uoffset) -> None: ...
def RawScanDataAddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: uoffset) -> None: ...
def RawScanDataAddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: uoffset) -> None: ...
def RawScanDataAddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: uoffset) -> None: ...
def RawScanDataAddWavelengthLog(builder: flatbuffers.Builder, wavelengthLog: uoffset) -> None: ...
def RawScanDataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

