# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Raw

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Raw.RawPowerLog import RawPowerLog
from Santec.STSProcess.Process.Native.Raw.RawPowerMonitorLog import RawPowerMonitorLog
from Santec.STSProcess.Process.Native.Raw.RawTriggerLog import RawTriggerLog
from Santec.STSProcess.Process.Native.Raw.RawWavelengthLog import RawWavelengthLog
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from Santec.STSProcess.Process.Native.Result.SweepInfo import SweepInfo
from typing import Optional
np = import_numpy()

class RawScanData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RawScanData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRawScanData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RawScanData
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RawScanData
    def Key(self) -> Optional[RawDataKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawDataKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def SweepData(self) -> Optional[SweepInfo]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = SweepInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def PowerLog(self) -> Optional[RawPowerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawPowerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def PowerTriggerLog(self) -> Optional[RawTriggerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawTriggerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def PowerMonitorLog(self) -> Optional[RawPowerMonitorLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawPowerMonitorLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def PowerMonitorTriggerLog(self) -> Optional[RawTriggerLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawTriggerLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanData
    def WavelengthLog(self) -> Optional[RawWavelengthLog]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawWavelengthLog()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RawScanDataStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    RawScanDataStart(builder)

def RawScanDataAddKey(builder: flatbuffers.Builder, key: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder: flatbuffers.Builder, key: int):
    RawScanDataAddKey(builder, key)

def RawScanDataAddSweepData(builder: flatbuffers.Builder, sweepData: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sweepData), 0)

def AddSweepData(builder: flatbuffers.Builder, sweepData: int):
    RawScanDataAddSweepData(builder, sweepData)

def RawScanDataAddPowerLog(builder: flatbuffers.Builder, powerLog: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(powerLog), 0)

def AddPowerLog(builder: flatbuffers.Builder, powerLog: int):
    RawScanDataAddPowerLog(builder, powerLog)

def RawScanDataAddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(powerTriggerLog), 0)

def AddPowerTriggerLog(builder: flatbuffers.Builder, powerTriggerLog: int):
    RawScanDataAddPowerTriggerLog(builder, powerTriggerLog)

def RawScanDataAddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(powerMonitorLog), 0)

def AddPowerMonitorLog(builder: flatbuffers.Builder, powerMonitorLog: int):
    RawScanDataAddPowerMonitorLog(builder, powerMonitorLog)

def RawScanDataAddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(powerMonitorTriggerLog), 0)

def AddPowerMonitorTriggerLog(builder: flatbuffers.Builder, powerMonitorTriggerLog: int):
    RawScanDataAddPowerMonitorTriggerLog(builder, powerMonitorTriggerLog)

def RawScanDataAddWavelengthLog(builder: flatbuffers.Builder, wavelengthLog: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(wavelengthLog), 0)

def AddWavelengthLog(builder: flatbuffers.Builder, wavelengthLog: int):
    RawScanDataAddWavelengthLog(builder, wavelengthLog)

def RawScanDataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RawScanDataEnd(builder)
