# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Raw

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from Santec.STSProcess.Process.Native.Raw.RawScanData import RawScanData
from Santec.STSProcess.Process.Native.Result.RawDataKey import RawDataKey
from typing import Optional
np = import_numpy()

class RawScanDataSetEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RawScanDataSetEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRawScanDataSetEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RawScanDataSetEntry
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RawScanDataSetEntry
    def Key(self) -> Optional[RawDataKey]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawDataKey()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RawScanDataSetEntry
    def Data(self) -> Optional[RawScanData]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = RawScanData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RawScanDataSetEntryStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    RawScanDataSetEntryStart(builder)

def RawScanDataSetEntryAddKey(builder: flatbuffers.Builder, key: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder: flatbuffers.Builder, key: int):
    RawScanDataSetEntryAddKey(builder, key)

def RawScanDataSetEntryAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    RawScanDataSetEntryAddData(builder, data)

def RawScanDataSetEntryEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RawScanDataSetEntryEnd(builder)
