from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.TriggerLogSource import TriggerLogSource

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawTriggerLog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawTriggerLog: ...
  @classmethod
  def GetRootAsRawTriggerLog(cls, buf: bytes, offset: int) -> RawTriggerLog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Source(self) -> typing.Literal[TriggerLogSource.Unknown, TriggerLogSource.Generated, TriggerLogSource.SPU, TriggerLogSource.MPM]: ...
def RawTriggerLogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawTriggerLogAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawTriggerLogStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RawTriggerLogAddSource(builder: flatbuffers.Builder, source: typing.Literal[TriggerLogSource.Unknown, TriggerLogSource.Generated, TriggerLogSource.SPU, TriggerLogSource.MPM]) -> None: ...
def RawTriggerLogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

