from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from Santec.STSProcess.Process.Native.Common.WavelengthLogSource import WavelengthLogSource

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RawWavelengthLog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RawWavelengthLog: ...
  @classmethod
  def GetRootAsRawWavelengthLog(cls, buf: bytes, offset: int) -> RawWavelengthLog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
  def Unit(self) -> int: ...
  def Source(self) -> typing.Literal[WavelengthLogSource.Unknown, WavelengthLogSource.TSL]: ...
def RawWavelengthLogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RawWavelengthLogAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def RawWavelengthLogStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RawWavelengthLogAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def RawWavelengthLogAddSource(builder: flatbuffers.Builder, source: typing.Literal[WavelengthLogSource.Unknown, WavelengthLogSource.TSL]) -> None: ...
def RawWavelengthLogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

